# Generated by Django 5.2.9 on 2026-01-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos',
            options={'verbose_name_plural': 'Documentos'},
        ),
        migrations.RenameField(
            model_name='documentos',
            old_name='data_criacao',
            new_name='data',
        ),
    ]
