# Generated by Django 5.2.9 on 2026-01-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='documentos',
            name='link',
            field=models.URLField(default='#'),
        ),
    ]
