# Generated by Django 5.2.9 on 2026-01-06 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_documentos_player_documentos_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='permitidos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_permitidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
