# Generated by Django 5.2.9 on 2026-01-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentos_permitidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='link',
            field=models.URLField(),
        ),
    ]
