# Generated by Django 5.2.9 on 2026-01-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_documentos_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='link',
        ),
        migrations.AddField(
            model_name='documentos',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='documentos/'),
        ),
    ]
