# Generated by Django 5.2.9 on 2026-01-09 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ataques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('acerto', models.CharField(max_length=50)),
                ('dano', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ataques',
            },
        ),
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modificado_atributo', models.CharField(choices=[('Força', 'Força'), ('Destreza', 'Destreza'), ('Constituição', 'Constituição'), ('Inteligência', 'Inteligência'), ('Sabedoria', 'Sabedoria'), ('Carisma', 'Carisma'), ('CA', 'CA'), ('Iniciativa', 'Iniciativa'), ('deslocamento', 'deslocamento'), ('max_pv', 'vida máxima'), ('dano_perfurante', 'dano a perfurante'), ('dano_cortante', 'dano a cortante'), ('dano_contundente', 'dano a contundente'), ('dano_fogo', 'dano a fogo'), ('dano_frio', 'dano a frio'), ('dano_eletricidade', 'dano a eletricidade'), ('dano_veneno', 'dano a veneno'), ('dano_necrotico', 'dano a necrotico'), ('dano_radiante', 'dano a radiante'), ('dano_psiquico', 'dano a psiquico'), ('res_perfurante', 'resistencia a perfurante'), ('res_cortante', 'resistencia a cortante'), ('res_contundente', 'resistencia a contundente'), ('res_fogo', 'resistencia a fogo'), ('res_frio', 'resistencia a frio'), ('res_eletricidade', 'resistencia a eletricidade'), ('res_veneno', 'resistencia a veneno'), ('res_necrotico', 'resistencia a necrotico'), ('res_radiante', 'resistencia a radiante'), ('res_psiquico', 'resistencia a psiquico'), ('Esp1', 'Especial 1'), ('Esp2', 'Especial 2'), ('Esp3', 'Especial 3')])),
                ('multiplicador', models.FloatField()),
                ('modificador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao', models.IntegerField()),
                ('buff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.buff')),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('buff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.buff')),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='RPGmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('jogadores', models.ManyToManyField(related_name='jogadores', to=settings.AUTH_USER_MODEL)),
                ('mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mestre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RPG',
                'verbose_name_plural': 'RPGS',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(blank=True, max_length=100)),
                ('antecedente', models.CharField(blank=True, max_length=100)),
                ('raça', models.CharField(max_length=100)),
                ('alinhamento', models.CharField(blank=True, max_length=100)),
                ('experiencia', models.IntegerField(default=0)),
                ('inspiração', models.IntegerField(default=0)),
                ('pontos_de_vida_maximos', models.IntegerField(default=0)),
                ('dado_de_vida', models.CharField(default='0', max_length=20)),
                ('força', models.IntegerField(default=0)),
                ('destreza', models.IntegerField(default=0)),
                ('constituição', models.IntegerField(default=0)),
                ('inteligencia', models.IntegerField(default=0)),
                ('sabedoria', models.IntegerField(default=0)),
                ('carisma', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
                ('rpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='rpg.rpgmodel')),
            ],
        ),
    ]
