# Generated by Django 5.2.9 on 2026-02-17 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('classe', models.CharField(blank=True, max_length=100, null=True)),
                ('antecedente', models.CharField(blank=True, max_length=100, null=True)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('alinhamento', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia', models.IntegerField(blank=True, default=0, null=True)),
                ('inspiracao', models.IntegerField(blank=True, default=0, null=True)),
                ('max_pv', models.IntegerField(blank=True, default=0, null=True)),
                ('temp_pv', models.IntegerField(blank=True, default=0, null=True)),
                ('atual_pv', models.IntegerField(blank=True, default=None, null=True)),
                ('i_pv', models.IntegerField(blank=True, default=0, null=True)),
                ('dado_de_vida', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('bonus_de_proficiencia', models.IntegerField(blank=True, default=0, null=True)),
                ('forca', models.IntegerField(blank=True, default=0, null=True)),
                ('destreza', models.IntegerField(blank=True, default=0, null=True)),
                ('constituicao', models.IntegerField(blank=True, default=0, null=True)),
                ('inteligencia', models.IntegerField(blank=True, default=0, null=True)),
                ('sabedoria', models.IntegerField(blank=True, default=0, null=True)),
                ('carisma', models.IntegerField(blank=True, default=0, null=True)),
                ('prof_check', models.JSONField(blank=True, default=list)),
                ('morte', models.BooleanField(default=False)),
                ('textao', models.TextField(blank=True, null=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ataques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ataque', models.CharField(blank=True, max_length=100, null=True)),
                ('acerto_ataque', models.CharField(blank=True, max_length=50, null=True)),
                ('dano_ataque', models.CharField(blank=True, max_length=50, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.ficha')),
            ],
            options={
                'verbose_name_plural': 'Ataques',
            },
        ),
        migrations.CreateModel(
            name='RPGmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpg_nome', models.CharField(max_length=100)),
                ('jogadores', models.ManyToManyField(related_name='jogadores', to=settings.AUTH_USER_MODEL)),
                ('mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mestre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RPG',
                'verbose_name_plural': 'RPGS',
            },
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('atributo_modificado', models.CharField(blank=True, choices=[('forca', 'Força'), ('destreza', 'Destreza'), ('constituicao', 'Constituição'), ('inteligencia', 'Inteligência'), ('sabedoria', 'Sabedoria'), ('carisma', 'Carisma'), ('acrobacia', 'Acrobacia'), ('arcanismo', 'Arcanismo'), ('atletismo', 'Atletismo'), ('atuacao', 'Atuação'), ('enganacao', 'Enganação'), ('furtividade', 'Furtividade'), ('historia', 'História'), ('intimidacao', 'Intimidação'), ('intuicao', 'Intuição'), ('investigacao', 'Investigação'), ('animais', 'Adestrar Animais'), ('medicina', 'Medicina'), ('natureza', 'Natureza'), ('percepcao', 'Percepção'), ('persuasao', 'Persuasão'), ('prestidigitacao', 'Prestidigitação'), ('religiao', 'Religião'), ('sobrevivencia', 'Sobrevivência'), ('ca', 'CA'), ('iniciativa', 'Iniciativa'), ('deslocamento', 'Deslocamento'), ('max_pv', 'Vida Máxima'), ('dano_perfurante', 'Dano a Perfurante'), ('dano_cortante', 'Dano a Cortante'), ('dano_contundente', 'Dano a Contundente'), ('dano_fogo', 'Dano a Fogo'), ('dano_frio', 'Dano a Frio'), ('dano_eletricidade', 'Dano a Eletricidade'), ('dano_veneno', 'Dano a Veneno'), ('dano_necrotico', 'Dano a Necrótico'), ('dano_radiante', 'Dano a Radiante'), ('dano_psiquico', 'Dano a Psíquico'), ('res_perfurante', 'Resistência a Perfurante'), ('res_cortante', 'Resistência a Cortante'), ('res_contundente', 'Resistência a Contundente'), ('res_fogo', 'Resistência a Fogo'), ('res_frio', 'Resistência a Frio'), ('res_eletricidade', 'Resistência a Eletricidade'), ('res_veneno', 'Resistência a Veneno'), ('res_necrotico', 'Resistência a Necrótico'), ('res_radiante', 'Resistência a Radiante'), ('res_psiquico', 'Resistência a Psíquico')], null=True)),
                ('modificador', models.IntegerField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/itens')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.ficha')),
                ('rpg_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.rpgmodel')),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.AddField(
            model_name='ficha',
            name='rpg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='rpg.rpgmodel'),
        ),
    ]
