# Generated by Django 5.2.9 on 2026-02-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='atributo_modificado',
            field=models.CharField(blank=True, choices=[('brutforca', 'Força'), ('brutdestreza', 'Destreza'), ('brutconstituicao', 'Constituição'), ('brutinteligencia', 'Inteligência'), ('brutsabedoria', 'Sabedoria'), ('brutcarisma', 'Carisma'), ('salvaforca', 'Salva_Força'), ('salvadestreza', 'Salva_Destreza'), ('salvaconstituicao', 'Salva_Constituição'), ('salvainteligencia', 'Salva_Inteligência'), ('salvasabedoria', 'Salva_Sabedoria'), ('salvacarisma', 'Salva_Carisma'), ('acrobacia', 'Acrobacia'), ('arcanismo', 'Arcanismo'), ('atletismo', 'Atletismo'), ('atuacao', 'Atuação'), ('enganacao', 'Enganação'), ('furtividade', 'Furtividade'), ('historia', 'História'), ('intimidacao', 'Intimidação'), ('intuicao', 'Intuição'), ('investigacao', 'Investigação'), ('animais', 'Adestrar Animais'), ('medicina', 'Medicina'), ('natureza', 'Natureza'), ('percepcao', 'Percepção'), ('persuasao', 'Persuasão'), ('prestidigitacao', 'Prestidigitação'), ('religiao', 'Religião'), ('sobrevivencia', 'Sobrevivência'), ('ca', 'CA'), ('iniciativa', 'Iniciativa'), ('deslocamento', 'Deslocamento'), ('max_pv', 'Vida Máxima'), ('dano_perfurante', 'Dano a Perfurante'), ('dano_cortante', 'Dano a Cortante'), ('dano_contundente', 'Dano a Contundente'), ('dano_fogo', 'Dano a Fogo'), ('dano_frio', 'Dano a Frio'), ('dano_eletricidade', 'Dano a Eletricidade'), ('dano_veneno', 'Dano a Veneno'), ('dano_necrotico', 'Dano a Necrótico'), ('dano_radiante', 'Dano a Radiante'), ('dano_psiquico', 'Dano a Psíquico'), ('res_perfurante', 'Resistência a Perfurante'), ('res_cortante', 'Resistência a Cortante'), ('res_contundente', 'Resistência a Contundente'), ('res_fogo', 'Resistência a Fogo'), ('res_frio', 'Resistência a Frio'), ('res_eletricidade', 'Resistência a Eletricidade'), ('res_veneno', 'Resistência a Veneno'), ('res_necrotico', 'Resistência a Necrótico'), ('res_radiante', 'Resistência a Radiante'), ('res_psiquico', 'Resistência a Psíquico')], null=True),
        ),
        migrations.AlterField(
            model_name='itens',
            name='modificador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
