# Generated by Django 5.2.9 on 2026-01-10 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpgmodel',
            old_name='nome',
            new_name='rpg_nome',
        ),
        migrations.AddField(
            model_name='ataques',
            name='ficha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rpg.ficha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='rpg_nome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rpg.rpgmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habilidades',
            name='ficha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rpg.ficha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itens',
            name='ficha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rpg.ficha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buff',
            name='modificador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buff',
            name='multiplicador',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
