# Generated by Django 5.2.9 on 2026-01-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_rename_nome_rpgmodel_rpg_nome_ataques_ficha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='rpg_nome',
        ),
    ]
