# Generated by Django 5.2.9 on 2026-01-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_remove_ficha_rpg_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='alinhamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='antecedente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='classe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='raça',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
