# Generated by Django 5.2.9 on 2026-01-10 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0004_alter_ficha_alinhamento_alter_ficha_antecedente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='raça',
            new_name='raca',
        ),
    ]
