# Generated by Django 5.2.9 on 2026-02-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0004_alter_itens_atributo_modificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpgmodel',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
