# Generated by Django 5.2.9 on 2026-02-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_rpgmodel_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpgmodel',
            name='log',
        ),
    ]
