# Generated by Django 5.2.9 on 2026-01-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_rename_raça_ficha_raca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='constituição',
            new_name='constituicao',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='força',
            new_name='forca',
        ),
    ]
