# Generated by Django 5.2.9 on 2026-01-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_rename_constituição_ficha_constituicao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='inspiração',
            new_name='inspiracao',
        ),
    ]
