# Generated by Django 5.2.9 on 2026-02-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_remove_rpgmodel_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='atributo_modificado_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
