# Generated by Django 5.2.9 on 2026-03-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0007_itens_atributo_modificado_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='temp_pv',
        ),
        migrations.AlterField(
            model_name='itens',
            name='atributo_modificado',
            field=models.CharField(blank=True, choices=[('atrforca', 'Força'), ('atrdestreza', 'Destreza'), ('atrconstituicao', 'Constituição'), ('atrinteligencia', 'Inteligência'), ('atrsabedoria', 'Sabedoria'), ('atrcarisma', 'Carisma'), ('salvaforca', 'Salva_Força'), ('salvadestreza', 'Salva_Destreza'), ('salvaconstituicao', 'Salva_Constituição'), ('salvainteligencia', 'Salva_Inteligência'), ('salvasabedoria', 'Salva_Sabedoria'), ('salvacarisma', 'Salva_Carisma'), ('periacrobacia', 'Acrobacia'), ('periarcanismo', 'Arcanismo'), ('periatletismo', 'Atletismo'), ('periatuacao', 'Atuação'), ('perienganacao', 'Enganação'), ('perifurtividade', 'Furtividade'), ('perihistoria', 'História'), ('periintimidacao', 'Intimidação'), ('periintuicao', 'Intuição'), ('periinvestigacao', 'Investigação'), ('perianimais', 'Adestrar Animais'), ('perimedicina', 'Medicina'), ('perinatureza', 'Natureza'), ('peripercepcao', 'Percepção'), ('peripersuasao', 'Persuasão'), ('periprestidigitacao', 'Prestidigitação'), ('perireligiao', 'Religião'), ('perisobrevivencia', 'Sobrevivência'), ('ca', 'CA'), ('iniciativa', 'Iniciativa'), ('deslocamento', 'Deslocamento'), ('max_pv', 'Vida Máxima')], null=True),
        ),
    ]
