# Generated by Django 5.2.9 on 2026-01-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0007_rename_inspiração_ficha_inspiracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='pontos_de_vida_maximos',
            new_name='max_pv',
        ),
    ]
