# Generated by Django 5.2.9 on 2026-01-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0008_rename_pontos_de_vida_maximos_ficha_max_pv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='carisma',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='constituicao',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='destreza',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='forca',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='inteligencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='rpg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='rpg.rpgmodel'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sabedoria',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
