# Generated by Django 5.2.9 on 2026-06-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0008_remove_ficha_temp_pv_alter_itens_atributo_modificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpgmodel',
            name='key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
