# Generated by Django 5.2.9 on 2026-01-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0009_alter_ficha_carisma_alter_ficha_constituicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='prof_check',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
