# Generated by Django 5.2.9 on 2026-06-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0009_rpgmodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpgmodel',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
