# Generated by Django 5.2.9 on 2026-06-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0010_alter_rpgmodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpgmodel',
            name='key',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
