# Generated by Django 5.2.9 on 2026-01-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0010_ficha_prof_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='prof_check',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
