# Generated by Django 5.2.9 on 2026-01-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0011_alter_ficha_prof_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='bonus_de_proficiencia',
            field=models.IntegerField(default=0),
        ),
    ]
