# Generated by Django 5.2.9 on 2026-06-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0011_alter_rpgmodel_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
