# Generated by Django 5.2.9 on 2026-01-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0012_ficha_bonus_de_proficiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='bonus_de_proficiencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='inspiracao',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
