# Generated by Django 5.2.9 on 2026-06-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0012_itens_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='equipado',
            field=models.BooleanField(default=False),
        ),
    ]
