# Generated by Django 5.2.9 on 2026-01-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0013_alter_ficha_bonus_de_proficiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='dado_de_vida',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='max_pv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
