# Generated by Django 5.2.9 on 2026-01-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0014_alter_ficha_dado_de_vida_alter_ficha_max_pv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='experiencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
