# Generated by Django 5.2.9 on 2026-01-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0015_alter_ficha_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='i_pv',
            field=models.IntegerField(default=0),
        ),
    ]
