# Generated by Django 5.2.9 on 2026-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0016_ficha_i_pv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='i_pv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
