# Generated by Django 5.2.9 on 2026-02-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0017_alter_ficha_i_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='temp_pv',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
