# Generated by Django 5.2.9 on 2026-02-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0018_ficha_temp_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='atual_pv',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
