# Generated by Django 5.2.9 on 2026-02-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0019_ficha_atual_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='morte',
            field=models.BooleanField(default=False),
        ),
    ]
