# Generated by Django 5.2.9 on 2026-02-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0020_ficha_morte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ataques',
            old_name='nome',
            new_name='nome_hab',
        ),
    ]
