# Generated by Django 5.2.9 on 2026-02-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0021_rename_nome_ataques_nome_hab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ataques',
            old_name='acerto',
            new_name='acerto_ataque',
        ),
        migrations.RenameField(
            model_name='ataques',
            old_name='dano',
            new_name='dano_ataque',
        ),
        migrations.RenameField(
            model_name='ataques',
            old_name='nome_hab',
            new_name='nome_ataque',
        ),
    ]
