# Generated by Django 5.2.9 on 2026-02-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0022_rename_acerto_ataques_acerto_ataque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='textao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
