# Generated by Django 5.2.9 on 2026-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0023_ficha_textao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ataques',
            name='acerto_ataque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ataques',
            name='dano_ataque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ataques',
            name='nome_ataque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
