# Generated by Django 5.2.9 on 2026-01-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
