# Generated by Django 5.2.9 on 2026-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='data',
            new_name='login_data',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='nome',
            new_name='player_nome',
        ),
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AddField(
            model_name='login',
            name='player_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
