# Generated by Django 5.2.9 on 2026-01-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_rename_data_login_login_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'Logins'},
        ),
        migrations.AlterField(
            model_name='login',
            name='player_nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome'),
        ),
    ]
