# Generated by Django 5.2.9 on 2026-01-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_alter_login_options_alter_login_player_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
