# Generated by Django 5.2.9 on 2026-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='documentos/documents'),
        ),
    ]
