# Generated by Django 5.2.9 on 2026-02-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentos_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
