# Generated by Django 5.2.9 on 2026-02-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentos_publico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='publico',
        ),
    ]
